name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
#
#  steps:
#    - name: Homebrew build helpers install
#      run: brew bundle
#    - name: Show the currently detailed version of Xcode for CLI
#      run: xcode-select -p
#    - name: Show Build Settings
#      run: xcodebuild -project MiniToolEngine.xcodeproj -scheme MiniToolEngine

