name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Xcodebuild Action
      run: echo 'Build started'
      run: xcodebuild clean -project MiniToolEngine.xcodeproj -scheme MiniToolEngine
