name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Where I am
      run: |
        pwd
        
    - name: Step outside
      run: |
        cd ..
        
    - name: Where I am
      run: |
        pwd
      
    - name: Xcodebuild Action
      run: |
        xcodebuild clean -project MiniToolEngine.xcodeproj -scheme MiniToolEngine
