name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Show the currently detailed version of Xcode for CLI
        run: xcode-select -p
      - name: build and test
        run: xcodebuild clean test -scheme MiniToolEngine
